import puppeteer from 'puppeteer-core';
import * as fs from 'fs';
import * as path from 'path';

interface OPAResult {
  status: 'complete';
  strengths: string[];
  passion: string;
  career_paths: string[];
  reliability_score: number;
  advice: string;
}

interface GeneratePdfOptions {
  data: OPAResult;
  isRtl: boolean;
}

function escapeHtml(text: string): string {
  if (!text) return '';
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

function loadLocalFont(): string {
  const fontsDir = path.join(process.cwd(), 'server', 'fonts');
  
  const regularPath = path.join(fontsDir, 'Cairo-Regular.ttf');
  const boldPath = path.join(fontsDir, 'Cairo-Bold.ttf');
  const semiBoldPath = path.join(fontsDir, 'Cairo-SemiBold.ttf');
  
  let fontFace = '';
  
  if (fs.existsSync(regularPath)) {
    const regularBase64 = fs.readFileSync(regularPath).toString('base64');
    fontFace += `
      @font-face {
        font-family: 'Cairo';
        src: url(data:font/truetype;base64,${regularBase64}) format('truetype');
        font-weight: 400;
        font-style: normal;
      }
    `;
  }
  
  if (fs.existsSync(semiBoldPath)) {
    const semiBoldBase64 = fs.readFileSync(semiBoldPath).toString('base64');
    fontFace += `
      @font-face {
        font-family: 'Cairo';
        src: url(data:font/truetype;base64,${semiBoldBase64}) format('truetype');
        font-weight: 600;
        font-style: normal;
      }
    `;
  }
  
  if (fs.existsSync(boldPath)) {
    const boldBase64 = fs.readFileSync(boldPath).toString('base64');
    fontFace += `
      @font-face {
        font-family: 'Cairo';
        src: url(data:font/truetype;base64,${boldBase64}) format('truetype');
        font-weight: 700;
        font-style: normal;
      }
    `;
  }
  
  return fontFace;
}

function generateHtmlReport(data: OPAResult, isRtl: boolean): string {
  const labels = isRtl
    ? {
        title: 'سند - المستشار الاستراتيجي',
        strengths: 'نقاط القوة',
        passion: 'الشغف والدافع العميق',
        careerPaths: 'المسارات المهنية المقترحة',
        confidenceScore: 'نسبة الثقة',
        advice: 'النصيحة الاستراتيجية',
        footer: 'تم إنشاء هذا التقرير بواسطة سند - المستشار الاستراتيجي',
        methodology: 'Elite Strategic Career Consultant',
        generatedOn: 'تاريخ الإعداد',
        safe: 'آمن',
        growth: 'نمو',
        unique: 'فريد',
      }
    : {
        title: 'Sanad - Elite Strategic Consultant',
        strengths: 'Your Strengths',
        passion: 'Your Deep Passion & Drive',
        careerPaths: 'Recommended Career Paths',
        confidenceScore: 'Confidence Score',
        advice: 'Strategic Advice',
        footer: 'This report was generated by Sanad - Elite Strategic Consultant',
        methodology: 'Elite Strategic Career Consultant',
        generatedOn: 'Generated on',
        safe: 'Safe',
        growth: 'Growth',
        unique: 'Unique',
      };

  const currentDate = new Date().toLocaleDateString(isRtl ? 'ar-SA' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const getPathLabel = (index: number) => {
    switch (index) {
      case 0:
        return labels.safe;
      case 1:
        return labels.growth;
      default:
        return labels.unique;
    }
  };

  const getPathBadgeClass = (index: number) => {
    switch (index) {
      case 0:
        return 'badge-safe';
      case 1:
        return 'badge-growth';
      default:
        return 'badge-unique';
    }
  };

  const strengthsHtml = data.strengths
    .map((s) => `<span class="badge">${escapeHtml(s)}</span>`)
    .join('');

  const pathsHtml = data.career_paths
    .map(
      (p, index) => `
      <div class="path-item">
        <div class="path-number">${index + 1}</div>
        <div class="path-text">${escapeHtml(p)}</div>
        <span class="path-badge ${getPathBadgeClass(index)}">${getPathLabel(index)}</span>
      </div>
    `
    )
    .join('');

  const fontFace = loadLocalFont();

  return `<!DOCTYPE html>
<html lang="${isRtl ? 'ar' : 'en'}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${labels.title}</title>
  <style>
    ${fontFace}

    * {
      margin: 0;
      padding: 0;
      box-sizing: border-box;
    }

    html, body {
      font-family: 'Cairo', 'Segoe UI', Tahoma, sans-serif;
      font-size: 14px;
      line-height: 1.6;
      color: #1F2937;
      background: #FFFFFF;
      direction: ${isRtl ? 'rtl' : 'ltr'};
    }

    .page {
      width: 210mm;
      min-height: 297mm;
      padding: 25mm 20mm;
      margin: 0 auto;
      background: #FFFFFF;
      position: relative;
    }

    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 24px;
      padding-bottom: 16px;
      border-bottom: 3px solid #10B981;
    }

    .header-title {
      font-size: 28px;
      font-weight: 700;
      color: #10B981;
    }

    .header-date {
      font-size: 12px;
      color: #6B7280;
    }

    .score-container {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 16px;
      margin-bottom: 24px;
      padding: 20px;
      background: #F0FDF4;
      border-radius: 12px;
    }

    .score-value {
      font-size: 48px;
      font-weight: 700;
      color: #10B981;
    }

    .score-label {
      font-size: 16px;
      color: #6B7280;
    }

    .section {
      margin-bottom: 20px;
      padding: 20px;
      background: #F9FAFB;
      border-radius: 12px;
      border-${isRtl ? 'right' : 'left'}: 5px solid #10B981;
    }

    .section-title {
      font-size: 18px;
      font-weight: 700;
      color: #10B981;
      margin-bottom: 12px;
    }

    .section-content {
      font-size: 14px;
      color: #374151;
      line-height: 1.8;
    }

    .badges-container {
      display: flex;
      flex-wrap: wrap;
      gap: 10px;
    }

    .badge {
      display: inline-block;
      background: #10B981;
      color: #FFFFFF;
      padding: 8px 16px;
      border-radius: 20px;
      font-size: 13px;
      font-weight: 600;
    }

    .path-item {
      display: flex;
      align-items: center;
      gap: 12px;
      margin-bottom: 12px;
      padding: 14px;
      background: #ECFDF5;
      border-radius: 10px;
    }

    .path-number {
      width: 32px;
      height: 32px;
      border-radius: 50%;
      background: #10B981;
      color: #FFFFFF;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 14px;
      flex-shrink: 0;
    }

    .path-text {
      flex: 1;
      font-size: 14px;
      color: #1F2937;
      line-height: 1.6;
    }

    .path-badge {
      padding: 6px 12px;
      border-radius: 12px;
      font-size: 11px;
      font-weight: 600;
      flex-shrink: 0;
    }

    .badge-safe {
      background: #D1FAE5;
      color: #065F46;
    }

    .badge-growth {
      background: #FEF3C7;
      color: #92400E;
    }

    .badge-unique {
      background: #DBEAFE;
      color: #1E40AF;
    }

    .advice-box {
      margin-bottom: 24px;
      padding: 24px;
      background: #ECFDF5;
      border: 2px solid #10B981;
      border-radius: 16px;
    }

    .advice-title {
      font-size: 18px;
      font-weight: 700;
      color: #10B981;
      margin-bottom: 12px;
    }

    .advice-text {
      font-size: 15px;
      color: #1F2937;
      line-height: 1.9;
    }

    .footer {
      position: absolute;
      bottom: 20mm;
      left: 20mm;
      right: 20mm;
      text-align: center;
      font-size: 11px;
      color: #9CA3AF;
      padding-top: 16px;
      border-top: 1px solid #E5E7EB;
    }

    .footer p {
      margin-bottom: 4px;
    }

    @media print {
      .page {
        width: 100%;
        padding: 15mm;
      }
    }
  </style>
</head>
<body>
  <div class="page">
    <header class="header">
      <h1 class="header-title">${labels.title}</h1>
      <div class="header-date">${labels.generatedOn}: ${currentDate}</div>
    </header>

    <div class="score-container">
      <div class="score-value">${Math.round(data.reliability_score)}%</div>
      <div class="score-label">${labels.confidenceScore}</div>
    </div>

    <section class="section">
      <h2 class="section-title">${labels.strengths}</h2>
      <div class="badges-container">
        ${strengthsHtml}
      </div>
    </section>

    <section class="section">
      <h2 class="section-title">${labels.passion}</h2>
      <p class="section-content">${escapeHtml(data.passion)}</p>
    </section>

    <section class="section">
      <h2 class="section-title">${labels.careerPaths}</h2>
      ${pathsHtml}
    </section>

    <div class="advice-box">
      <h2 class="advice-title">${labels.advice}</h2>
      <p class="advice-text">${escapeHtml(data.advice)}</p>
    </div>

    <footer class="footer">
      <p>${labels.footer}</p>
      <p>${labels.methodology}</p>
      <p>${currentDate}</p>
    </footer>
  </div>
</body>
</html>`;
}

export async function generatePdf(options: GeneratePdfOptions): Promise<Buffer> {
  const { data, isRtl } = options;
  
  const browserlessApiKey = process.env.BROWSERLESS_API_KEY;
  
  if (!browserlessApiKey) {
    throw new Error('BROWSERLESS_API_KEY environment variable is not set');
  }
  
  const browserWSEndpoint = `wss://chrome.browserless.io?token=${browserlessApiKey}`;
  
  const html = generateHtmlReport(data, isRtl);

  const browser = await puppeteer.connect({
    browserWSEndpoint,
  });

  let page = null;
  try {
    page = await browser.newPage();

    await page.setViewport({
      width: 794,
      height: 1123,
      deviceScaleFactor: 2,
    });

    await page.setContent(html, {
      waitUntil: ['load', 'networkidle0'],
    });

    await page.evaluateHandle('document.fonts.ready');

    await new Promise((resolve) => setTimeout(resolve, 500));

    const pdfBuffer = await page.pdf({
      format: 'A4',
      printBackground: true,
      margin: {
        top: '0',
        right: '0',
        bottom: '0',
        left: '0',
      },
      preferCSSPageSize: true,
    });

    return Buffer.from(pdfBuffer);
  } finally {
    if (page) {
      await page.close().catch(() => {});
    }
    await browser.close().catch(() => {});
  }
}
