import { useState } from 'react';
import { Document, Page, Text, View, StyleSheet, Font, pdf } from '@react-pdf/renderer';
import { saveAs } from 'file-saver';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import type { OPAResult } from '@/lib/types';

// Use jsDelivr CDN for reliable font loading - bypasses Replit's local file serving issues
// Using TTF format which is more compatible with @react-pdf/renderer
Font.register({
  family: 'Cairo',
  src: 'https://cdn.jsdelivr.net/fontsource/fonts/cairo@latest/arabic-400-normal.ttf'
});

Font.register({
  family: 'Cairo-Bold',
  src: 'https://cdn.jsdelivr.net/fontsource/fonts/cairo@latest/arabic-700-normal.ttf'
});

const styles = StyleSheet.create({
  page: {
    fontFamily: 'Cairo',
    fontSize: 12,
    padding: 30,
    backgroundColor: '#FFFFFF',
    direction: 'rtl',
  },
  header: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 2,
    borderBottomColor: '#10B981',
  },
  headerTitle: {
    fontSize: 24,
    fontFamily: 'Cairo-Bold',
    color: '#10B981',
    textAlign: 'right',
  },
  headerDate: {
    fontSize: 10,
    color: '#6B7280',
    textAlign: 'left',
  },
  section: {
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#10B981',
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: 'Cairo-Bold',
    color: '#10B981',
    marginBottom: 10,
    textAlign: 'right',
  },
  sectionContent: {
    fontSize: 12,
    color: '#1F2937',
    textAlign: 'right',
    lineHeight: 1.6,
  },
  badgesContainer: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
  },
  badge: {
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 16,
    fontSize: 11,
  },
  pathItem: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    marginBottom: 8,
    padding: 10,
    backgroundColor: '#ECFDF5',
    borderRadius: 8,
  },
  pathNumber: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: '#10B981',
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: 'Cairo-Bold',
    textAlign: 'center',
    lineHeight: 28,
    marginLeft: 10,
  },
  pathText: {
    flex: 1,
    fontSize: 12,
    color: '#1F2937',
    textAlign: 'right',
  },
  pathBadge: {
    backgroundColor: '#D1FAE5',
    color: '#065F46',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 10,
    fontSize: 9,
    marginRight: 10,
  },
  adviceBox: {
    backgroundColor: '#ECFDF5',
    borderWidth: 2,
    borderColor: '#10B981',
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
  },
  adviceTitle: {
    fontSize: 16,
    fontFamily: 'Cairo-Bold',
    color: '#10B981',
    marginBottom: 10,
    textAlign: 'right',
  },
  adviceText: {
    fontSize: 13,
    color: '#1F2937',
    textAlign: 'right',
    lineHeight: 1.8,
  },
  scoreContainer: {
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
    padding: 15,
    backgroundColor: '#F0FDF4',
    borderRadius: 8,
  },
  scoreValue: {
    fontSize: 36,
    fontFamily: 'Cairo-Bold',
    color: '#10B981',
    marginLeft: 10,
  },
  scoreLabel: {
    fontSize: 14,
    color: '#6B7280',
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 9,
    color: '#9CA3AF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
    paddingTop: 10,
  },
  footerText: {
    marginBottom: 4,
  },
});

interface SanadReportPDFProps {
  data: OPAResult;
  isRtl: boolean;
}

function SanadReportPDF({ data, isRtl }: SanadReportPDFProps) {
  const labels = isRtl
    ? {
        title: 'سند - المستشار الاستراتيجي',
        strengths: 'نقاط القوة',
        passion: 'الشغف والدافع العميق',
        careerPaths: 'المسارات المهنية المقترحة',
        confidenceScore: 'نسبة الثقة',
        advice: 'النصيحة الاستراتيجية',
        footer: 'تم إنشاء هذا التقرير بواسطة سند - المستشار الاستراتيجي',
        methodology: 'Elite Strategic Career Consultant',
        generatedOn: 'تاريخ الإعداد',
        safe: 'آمن',
        growth: 'نمو',
        unique: 'فريد',
      }
    : {
        title: 'Sanad - Elite Strategic Consultant',
        strengths: 'Your Strengths',
        passion: 'Your Deep Passion & Drive',
        careerPaths: 'Recommended Career Paths',
        confidenceScore: 'Confidence Score',
        advice: 'Strategic Advice',
        footer: 'This report was generated by Sanad - Elite Strategic Consultant',
        methodology: 'Elite Strategic Career Consultant',
        generatedOn: 'Generated on',
        safe: 'Safe',
        growth: 'Growth',
        unique: 'Unique',
      };

  const currentDate = new Date().toLocaleDateString(isRtl ? 'ar-SA' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const getPathLabel = (index: number) => {
    switch (index) {
      case 0:
        return labels.safe;
      case 1:
        return labels.growth;
      default:
        return labels.unique;
    }
  };

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.headerTitle}>{labels.title}</Text>
          <Text style={styles.headerDate}>{labels.generatedOn}: {currentDate}</Text>
        </View>

        <View style={styles.scoreContainer}>
          <Text style={styles.scoreValue}>{data.reliability_score}%</Text>
          <Text style={styles.scoreLabel}>{labels.confidenceScore}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.strengths}</Text>
          <View style={styles.badgesContainer}>
            {data.strengths.map((strength, index) => (
              <Text key={index} style={styles.badge}>{strength}</Text>
            ))}
          </View>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.passion}</Text>
          <Text style={styles.sectionContent}>{data.passion}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>{labels.careerPaths}</Text>
          {data.career_paths.map((path, index) => (
            <View key={index} style={styles.pathItem}>
              <Text style={styles.pathNumber}>{index + 1}</Text>
              <Text style={styles.pathText}>{path}</Text>
              <Text style={styles.pathBadge}>{getPathLabel(index)}</Text>
            </View>
          ))}
        </View>

        <View style={styles.adviceBox}>
          <Text style={styles.adviceTitle}>{labels.advice}</Text>
          <Text style={styles.adviceText}>{data.advice}</Text>
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>{labels.footer}</Text>
          <Text style={styles.footerText}>{labels.methodology}</Text>
          <Text>{currentDate}</Text>
        </View>
      </Page>
    </Document>
  );
}

interface DownloadReportButtonProps {
  data: OPAResult | null;
  isRtl: boolean;
}

export function DownloadReportButton({ data, isRtl }: DownloadReportButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  
  const buttonLabel = isRtl ? 'تحميل التقرير PDF' : 'Download PDF Report';
  const loadingLabel = isRtl ? 'جاري تجهيز الملف...' : 'Generating PDF...';
  const fileName = isRtl ? 'تقرير-سند.pdf' : 'sanad-report.pdf';
  const errorMessage = isRtl 
    ? 'عذراً، حدث خطأ أثناء تجهيز الملف. يرجى المحاولة مرة أخرى.' 
    : 'Sorry, an error occurred while generating the file. Please try again.';

  const handleDownload = async () => {
    if (!data) return;
    
    try {
      setIsGenerating(true);
      
      console.log("Starting PDF generation...");
      const pdfDoc = pdf(<SanadReportPDF data={data} isRtl={isRtl} />);
      console.log("PDF document created, generating blob...");
      const blob = await pdfDoc.toBlob();
      console.log("Blob generated, size:", blob.size);
      
      saveAs(blob, fileName);
      console.log("PDF saved successfully");
      
    } catch (error: unknown) {
      const errorDetails = error instanceof Error 
        ? { message: error.message, stack: error.stack, name: error.name }
        : String(error);
      console.error("PDF Generation Failed - Details:", errorDetails);
      console.error("Full error object:", error);
      alert(errorMessage);
    } finally {
      setIsGenerating(false);
    }
  };

  if (!data) {
    return (
      <Button disabled data-testid="button-export-pdf">
        <FileDown className="h-4 w-4 me-2" />
        {buttonLabel}
      </Button>
    );
  }

  return (
    <Button 
      onClick={handleDownload} 
      disabled={isGenerating}
      data-testid="button-export-pdf"
    >
      {isGenerating ? (
        <Loader2 className="h-4 w-4 me-2 animate-spin" />
      ) : (
        <FileDown className="h-4 w-4 me-2" />
      )}
      {isGenerating ? loadingLabel : buttonLabel}
    </Button>
  );
}

export { SanadReportPDF };
