import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { FileDown, Loader2 } from 'lucide-react';
import type { OPAResult, DecisionData } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
// @ts-ignore - html2pdf.js doesn't have proper types
import html2pdf from 'html2pdf.js';

interface DownloadReportButtonProps {
  data: OPAResult | null;
  isRtl: boolean;
  decisionData?: DecisionData | null;
}

function generateReportHtml(data: OPAResult, isRtl: boolean, decisionData?: DecisionData | null): string {
  const labels = isRtl
    ? {
      title: 'سند - المستشار الاستراتيجي',
      strengths: 'نقاط القوة',
      passion: 'الشغف والدافع العميق',
      careerPaths: 'المسارات المهنية المقترحة',
      confidenceScore: 'نسبة الثقة',
      advice: 'النصيحة الاستراتيجية',
      footer: 'تم إنشاء هذا التقرير بواسطة سند',
      generatedOn: 'تاريخ الإعداد',
      safe: 'آمن',
      growth: 'نمو',
      unique: 'فريد',
      decisionContract: 'عقد القرار الاستراتيجي',
      primaryDirection: 'الاتجاه الرئيسي',
      reasons: 'الأسباب',
      stopList: 'قائمة التوقف',
      plan90Days: 'خطة 90 يوم',
      abortSignal: 'إشارة الانسحاب',
      opportunityCost: 'تكلفة الفرصة البديلة',
    }
    : {
      title: 'Sanad - Elite Strategic Consultant',
      strengths: 'Your Strengths',
      passion: 'Your Deep Passion & Drive',
      careerPaths: 'Recommended Career Paths',
      confidenceScore: 'Confidence Score',
      advice: 'Strategic Advice',
      footer: 'Generated by Sanad - Elite Strategic Consultant',
      generatedOn: 'Generated on',
      safe: 'Safe',
      growth: 'Growth',
      unique: 'Unique',
      decisionContract: 'Strategic Decision Contract',
      primaryDirection: 'Primary Direction',
      reasons: 'Key Reasons',
      stopList: 'Stop List',
      plan90Days: '90-Day Plan',
      abortSignal: 'Abort Signal',
      opportunityCost: 'Opportunity Cost',
    };

  const currentDate = new Date().toLocaleDateString(isRtl ? 'ar-SA' : 'en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  const getPathLabel = (index: number) => {
    switch (index) {
      case 0: return labels.safe;
      case 1: return labels.growth;
      default: return labels.unique;
    }
  };

  const strengthsHtml = data.strengths
    .map((s) => `<span class="badge">${s}</span>`)
    .join('');

  const pathsHtml = data.career_paths
    .map(
      (p, index) => `
      <div class="path-item">
        <div class="path-number">${index + 1}</div>
        <div class="path-text">${p}</div>
        <span class="path-badge">${getPathLabel(index)}</span>
      </div>
    `
    )
    .join('');

  // Decision Contract Section (if available)
  let decisionHtml = '';
  if (decisionData) {
    const reasonsHtml = decisionData.reasons.map(r => `<li>${r}</li>`).join('');
    const stopListHtml = decisionData.stop_list.map(s => `<li>${s}</li>`).join('');
    const planHtml = decisionData.plan_90_days.map((p, i) => `<li><strong>${isRtl ? 'الشهر' : 'Month'} ${i + 1}:</strong> ${p}</li>`).join('');

    decisionHtml = `
      <div class="decision-section">
        <h2 class="section-title decision-title">${labels.decisionContract}</h2>
        
        <div class="decision-primary">
          <span class="decision-label">${labels.primaryDirection}:</span>
          <span class="decision-value">${decisionData.primary_direction}</span>
        </div>

        <div class="decision-grid">
          <div class="decision-card">
            <h3>${labels.reasons}</h3>
            <ul>${reasonsHtml}</ul>
          </div>
          <div class="decision-card stop-card">
            <h3>${labels.stopList}</h3>
            <ul>${stopListHtml}</ul>
          </div>
        </div>

        <div class="decision-plan">
          <h3>${labels.plan90Days}</h3>
          <ol>${planHtml}</ol>
        </div>

        <div class="decision-meta">
          <div><strong>${labels.abortSignal}:</strong> ${decisionData.abort_signal}</div>
          <div><strong>${labels.opportunityCost}:</strong> ${decisionData.opportunity_cost}</div>
        </div>
      </div>
    `;
  }

  return `
<!DOCTYPE html>
<html lang="${isRtl ? 'ar' : 'en'}" dir="${isRtl ? 'rtl' : 'ltr'}">
<head>
  <meta charset="UTF-8">
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap');
    
    * { margin: 0; padding: 0; box-sizing: border-box; }
    
    body {
      font-family: 'Cairo', 'Segoe UI', sans-serif;
      font-size: 12px;
      line-height: 1.6;
      color: #1F2937;
      background: #FFFFFF;
      direction: ${isRtl ? 'rtl' : 'ltr'};
      padding: 20px;
    }
    
    .header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 20px;
      padding-bottom: 12px;
      border-bottom: 3px solid #10B981;
    }
    
    .header-title {
      font-size: 22px;
      font-weight: 700;
      color: #10B981;
    }
    
    .header-date {
      font-size: 10px;
      color: #6B7280;
    }
    
    .score-container {
      display: flex;
      justify-content: center;
      align-items: center;
      gap: 12px;
      margin-bottom: 20px;
      padding: 16px;
      background: #F0FDF4;
      border-radius: 10px;
    }
    
    .score-value {
      font-size: 36px;
      font-weight: 700;
      color: #10B981;
    }
    
    .score-label {
      font-size: 14px;
      color: #6B7280;
    }
    
    .section {
      margin-bottom: 16px;
      padding: 16px;
      background: #F9FAFB;
      border-radius: 10px;
      border-${isRtl ? 'right' : 'left'}: 4px solid #10B981;
    }
    
    .section-title {
      font-size: 14px;
      font-weight: 700;
      color: #10B981;
      margin-bottom: 10px;
    }
    
    .section-content {
      font-size: 12px;
      color: #374151;
      line-height: 1.7;
    }
    
    .badges-container {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
    }
    
    .badge {
      display: inline-block;
      background: #10B981;
      color: #FFFFFF;
      padding: 6px 12px;
      border-radius: 16px;
      font-size: 11px;
      font-weight: 600;
    }
    
    .path-item {
      display: flex;
      align-items: center;
      gap: 10px;
      margin-bottom: 10px;
      padding: 12px;
      background: #ECFDF5;
      border-radius: 8px;
    }
    
    .path-number {
      width: 28px;
      height: 28px;
      border-radius: 50%;
      background: #10B981;
      color: #FFFFFF;
      display: flex;
      align-items: center;
      justify-content: center;
      font-weight: 700;
      font-size: 12px;
      flex-shrink: 0;
    }
    
    .path-text {
      flex: 1;
      font-size: 12px;
      color: #1F2937;
    }
    
    .path-badge {
      padding: 4px 10px;
      border-radius: 10px;
      font-size: 10px;
      font-weight: 600;
      background: #D1FAE5;
      color: #065F46;
    }
    
    .advice-box {
      margin-bottom: 20px;
      padding: 20px;
      background: #ECFDF5;
      border: 2px solid #10B981;
      border-radius: 12px;
    }
    
    .advice-title {
      font-size: 14px;
      font-weight: 700;
      color: #10B981;
      margin-bottom: 10px;
    }
    
    .advice-text {
      font-size: 12px;
      color: #1F2937;
      line-height: 1.8;
    }
    
    /* Decision Contract Styles */
    .decision-section {
      margin-top: 24px;
      padding: 20px;
      background: linear-gradient(135deg, #F0FDF4 0%, #ECFDF5 100%);
      border: 2px solid #10B981;
      border-radius: 12px;
      page-break-inside: avoid;
    }
    
    .decision-title {
      font-size: 16px;
      text-align: center;
      margin-bottom: 16px;
      border-bottom: none;
    }
    
    .decision-primary {
      background: #10B981;
      color: white;
      padding: 12px 16px;
      border-radius: 8px;
      margin-bottom: 16px;
      text-align: center;
    }
    
    .decision-label {
      font-weight: 400;
      opacity: 0.9;
    }
    
    .decision-value {
      font-size: 16px;
      font-weight: 700;
      display: block;
      margin-top: 4px;
    }
    
    .decision-grid {
      display: flex;
      gap: 12px;
      margin-bottom: 16px;
    }
    
    .decision-card {
      flex: 1;
      background: white;
      padding: 12px;
      border-radius: 8px;
      border: 1px solid #D1FAE5;
    }
    
    .decision-card h3 {
      font-size: 12px;
      color: #10B981;
      margin-bottom: 8px;
    }
    
    .decision-card ul, .decision-card ol {
      padding-${isRtl ? 'right' : 'left'}: 16px;
      font-size: 11px;
    }
    
    .decision-card li {
      margin-bottom: 4px;
    }
    
    .stop-card {
      border-color: #FEE2E2;
    }
    
    .stop-card h3 {
      color: #DC2626;
    }
    
    .decision-plan {
      background: white;
      padding: 12px;
      border-radius: 8px;
      margin-bottom: 16px;
    }
    
    .decision-plan h3 {
      font-size: 12px;
      color: #10B981;
      margin-bottom: 8px;
    }
    
    .decision-plan ol {
      padding-${isRtl ? 'right' : 'left'}: 16px;
      font-size: 11px;
    }
    
    .decision-meta {
      display: flex;
      gap: 16px;
      font-size: 10px;
      color: #6B7280;
    }
    
    .decision-meta > div {
      flex: 1;
      background: #F9FAFB;
      padding: 8px;
      border-radius: 6px;
    }
    
    .footer {
      margin-top: 24px;
      text-align: center;
      font-size: 10px;
      color: #9CA3AF;
      padding-top: 12px;
      border-top: 1px solid #E5E7EB;
    }
  </style>
</head>
<body>
  <header class="header">
    <h1 class="header-title">${labels.title}</h1>
    <div class="header-date">${labels.generatedOn}: ${currentDate}</div>
  </header>

  <div class="score-container">
    <div class="score-value">${Math.round(data.reliability_score)}%</div>
    <div class="score-label">${labels.confidenceScore}</div>
  </div>

  <section class="section">
    <h2 class="section-title">${labels.strengths}</h2>
    <div class="badges-container">
      ${strengthsHtml}
    </div>
  </section>

  <section class="section">
    <h2 class="section-title">${labels.passion}</h2>
    <p class="section-content">${data.passion}</p>
  </section>

  <section class="section">
    <h2 class="section-title">${labels.careerPaths}</h2>
    ${pathsHtml}
  </section>

  <div class="advice-box">
    <h2 class="advice-title">${labels.advice}</h2>
    <p class="advice-text">${data.advice}</p>
  </div>

  ${decisionHtml}

  <footer class="footer">
    <p>${labels.footer}</p>
    <p>${currentDate}</p>
  </footer>
</body>
</html>`;
}

export function DownloadReportButton({ data, isRtl, decisionData }: DownloadReportButtonProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();
  const containerRef = useRef<HTMLDivElement>(null);

  const buttonLabel = isRtl ? 'تحميل التقرير PDF' : 'Download PDF Report';
  const loadingLabel = isRtl ? 'جاري تجهيز الملف...' : 'Generating PDF...';

  const handleDownload = async () => {
    if (!data) return;

    try {
      setIsGenerating(true);

      const htmlContent = generateReportHtml(data, isRtl, decisionData);

      // Create a temporary container
      const tempContainer = document.createElement('div');
      tempContainer.innerHTML = htmlContent;
      tempContainer.style.position = 'absolute';
      tempContainer.style.left = '-9999px';
      tempContainer.style.top = '0';
      document.body.appendChild(tempContainer);

      const element = tempContainer.querySelector('body') || tempContainer;

      const opt = {
        margin: 10,
        filename: isRtl ? 'تقرير-سند.pdf' : 'sanad-report.pdf',
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          letterRendering: true,
        },
        jsPDF: {
          unit: 'mm',
          format: 'a4',
          orientation: 'portrait'
        },
        pagebreak: { mode: ['avoid-all', 'css', 'legacy'] }
      };

      await html2pdf().set(opt).from(element).save();

      // Clean up
      document.body.removeChild(tempContainer);

      toast({
        title: isRtl ? 'تم توليد التقرير' : 'Report Generated',
        description: isRtl
          ? 'تم تحميل التقرير بنجاح'
          : 'Report downloaded successfully',
      });

    } catch (error: unknown) {
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      console.error('PDF Generation Failed:', error);

      toast({
        title: isRtl ? 'خطأ' : 'Error',
        description: isRtl
          ? `حدث خطأ أثناء توليد التقرير: ${errorMessage}`
          : `Failed to generate report: ${errorMessage}`,
        variant: 'destructive',
      });
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <>
      <div ref={containerRef} style={{ display: 'none' }} />
      <Button
        onClick={handleDownload}
        disabled={!data || isGenerating}
        data-testid="button-export-pdf"
      >
        {isGenerating ? (
          <Loader2 className="h-4 w-4 me-2 animate-spin" />
        ) : (
          <FileDown className="h-4 w-4 me-2" />
        )}
        {isGenerating ? loadingLabel : buttonLabel}
      </Button>
    </>
  );
}
